### PR TITLE
Get camera working in external view

### PR DESCRIPTION
**Pull request by ghost**
I got this working using a 2-axis camera control scheme based on `camHdg` and `camPitch`, similar to map mode. This always keeps the vessel centered on the screen, and moves the camera radially around it.

Just like in map mode, this doesn't play nicely with dragging the camera around with the mouse, but I have an idea for how to fix that.

A more immersive scheme than this would include a roll axis and fix the camera in space, allowing the player to look away from the vessel. I think it would be fun to fly aircraft like this, w/ the camera fixed in a chase position, allowing the player to look around at the scenery, but this is good enough for now.

### CODE REVIEW

**Comment by JonnyOThan** [comment]
Yeah, I suspect that the root cause of #1 is the FlightCamera overwriting the camera transform.  This is something I had to deal with in FreeIva and KerbalVR.  By manipulating camHdg and camPitch you're just feeding the FlightCamera different inputs, working around the issue.

This is fine - I'll have to see how it feels, but I think I'd prefer more of the kerbalvr experience (what you get when the game is paused)

**Comment by JonnyOThan** [comment]
Yeah...this isn't how I'd like the tracking to behave.

**Comment by ghost** [comment]
@JonnyOThan I agree, it's not ideal, but it's an improvement over not working at all, lol. Can you describe a scheme that would be better? Maybe something similar to what I described in the top comment?

**Comment by JonnyOThan** [comment]
I think an approach that would work is inserting a gameobject as the parent of the camera and then manipulating that transform with kerbtrack.

**Comment by ghost** [comment]
Yeah, I think something like that might work. Not sure how to insert something new as the parent of the camera, but it will probably become apparent the more I work w/ Unity/KSP.

**Pull request merged**
